services:
  - type: web
    name: dbmaster-studio
    runtime: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm run start
    publishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RECOVERY_EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
